/*
 * This linker command file is to be included if user wants to use the DCSM
 * (Dual Zone Code Security Module) feature on the device. This linker command
 * file works as an addendum to the main Flash/RAM linker command file.
 * The sections in the dcsm.asm source file in this project are linked as per
 * the commands given in the file.
 *
 * This file was originally generated by the DCSM Tool and then edited to
 * remove sections not used by the sdl_ex_dcsm_ffi example. We strongly
 * recommend using this tool to generate the code for your DCSM configuration.
 * Refer to the following guide for more information:
 * http://www.ti.com/lit/pdf/spracp8
 *
 * Once users are confident that they want to program the passwords in OTP,
 * the DSECT section type can be removed.
 *
 */

MEMORY
{
PAGE 0 :  /* Program Memory */

   /* Z1 OTP.  LinkPointers */
   DCSM_OTP_Z1_LINKPOINTER      : origin = 0x78000, length = 0x00000C

   /* DCSM Z1 Zone Select Contents (!!Movable!!) */
   /* Z1 OTP.  Z1 password locations / Flash and RAM partitioning */
   DCSM_ZSEL_Z1_P0              : origin = 0x78020, length = 0x000010

   /* Z2 OTP.  LinkPointers */
   DCSM_OTP_Z2_LINKPOINTER      : origin = 0x78200, length = 0x00000C

   /* DCSM Z1 Zone Select Contents (!!Movable!!) */
   /* Z2 OTP.  Z2 password locations / Flash and RAM partitioning  */
   DCSM_ZSEL_Z2_P0              : origin = 0x78220, length = 0x000010
}

SECTIONS
{
   /* Remove the DSECT when you're ready to permanantly write to these
      sections. Make sure you've also uncommented the .asm file! */
   dcsm_otp_z1_linkpointer  : > DCSM_OTP_Z1_LINKPOINTER, PAGE = 0, type = DSECT
   dcsm_zsel_z1             : > DCSM_ZSEL_Z1_P0,         PAGE = 0, type = DSECT

   dcsm_otp_z2_linkpointer  : > DCSM_OTP_Z2_LINKPOINTER, PAGE = 0, type = DSECT
   dcsm_zsel_z2             : > DCSM_ZSEL_Z2_P0,         PAGE = 0, type = DSECT
}

/*
//===========================================================================
// End of file.
//===========================================================================
*/
