;;//###########################################################################
;;//
;;// FILE:  f28004x_dcsm.asm
;;//
;;//###########################################################################
;;//
;;// This file was originally generated by the DCSM Tool and then edited to
;;// remove sections not used by the sdl_ex_dcsm_ffi example. We strongly
;;// recommend using this tool to generate the code for your DCSM configuration.
;;// Refer to the following guide for more information:
;;// http://www.ti.com/lit/pdf/spracp8
;;//
;;//###########################################################################
;;// $TI Release: C2000 Diagnostic Library v2.01.00 $
;;// $Release Date: Fri Feb 12 19:23:23 IST 2021 $
;;// $Copyright:
;// Copyright (C) 2021 Texas Instruments Incorporated - http://www.ti.com/
;//
;// Redistribution and use in source and binary forms, with or without 
;// modification, are permitted provided that the following conditions 
;// are met:
;// 
;//   Redistributions of source code must retain the above copyright 
;//   notice, this list of conditions and the following disclaimer.
;// 
;//   Redistributions in binary form must reproduce the above copyright
;//   notice, this list of conditions and the following disclaimer in the 
;//   documentation and/or other materials provided with the   
;//   distribution.
;// 
;//   Neither the name of Texas Instruments Incorporated nor the names of
;//   its contributors may be used to endorse or promote products derived
;//   from this software without specific prior written permission.
;// 
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
;// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
;// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
;// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
;// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
;// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
;// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
;// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
;// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
;// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
;// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;// $
;;//###########################################################################

;----------------------------------------------------------------------
; Zone 1
;----------------------------------------------------------------------
    .sect "dcsm_otp_z1_linkpointer"
     .retain
;      .long 0x1FFFFFFF
;      .long 0xFFFFFFFF     ; Reserved
;      .long 0x1FFFFFFF
;      .long 0xFFFFFFFF     ; Reserved
;      .long 0x1FFFFFFF
;      .long 0xFFFFFFFF     ; Reserved

    .sect "dcsm_zsel_z1"
     .retain
;      .long 0x000000FF       ; Z1-EXEONLYRAM
;      .long 0x0000FFFF      ; Z1-EXEONLYSECT
;      .long 0x0000AA9A          ; Z1-GRABRAM - Secure only LS2 in Z1
;      .long 0xAAAAA6AA         ; Z1-GRABSECT - Secure only B0 SECT 5

;      .long 0xFFFFFFFF
;      .long 0x47FFFFFF
;      .long 0xFFFFFFFF
;      .long 0xFFFFFFFF

;----------------------------------------------------------------------
; Zone 2
;----------------------------------------------------------------------
    .sect "dcsm_otp_z2_linkpointer"
     .retain
;      .long 0x1FFFFFFF
;      .long 0xFFFFFFFF     ; Reserved
;      .long 0x1FFFFFFF
;      .long 0xFFFFFFFF     ; Reserved
;      .long 0x1FFFFFFF
;      .long 0xFFFFFFFF     ; Reserved

    .sect "dcsm_zsel_z2"
     .retain
;      .long 0x000000FF       ; Z2-EXEONLYRAM
;      .long 0x0000FFFF      ; Z2-EXEONLYSECT
;      .long 0x0000A9AA          ; Z2-GRABRAM - Secure only LS4 in Z2
;      .long 0xAAAA9AAA         ; Z2-GRABSECT - Secure only B0 SECT6

;      .long 0xFFFFFFFF
;      .long 0xE3FFFFFF
;      .long 0xFFFFFFFF
;      .long 0xFFFFFFFF

;----------------------------------------------------------------------
; End of file
;----------------------------------------------------------------------

