let ECAP_EmulationMode = [
	{ name: "ECAP_EMULATION_STOP", displayName: "EMULATION STOP" },
	{ name: "ECAP_EMULATION_RUN_TO_ZERO", displayName: "EMULATION RUN TO ZERO" },
	{ name: "ECAP_EMULATION_FREE_RUN", displayName: "EMULATION FREE RUN" },
]
let ECAP_CaptureMode = [
	{ name: "ECAP_CONTINUOUS_CAPTURE_MODE", displayName: "CONTINUOUS CAPTURE MODE" },
	{ name: "ECAP_ONE_SHOT_CAPTURE_MODE", displayName: "ONE SHOT CAPTURE MODE" },
]
let ECAP_Events = [
	{ name: "ECAP_EVENT_1", displayName: "eCAP event 1" },
	{ name: "ECAP_EVENT_2", displayName: "eCAP event 2" },
	{ name: "ECAP_EVENT_3", displayName: "eCAP event 3" },
	{ name: "ECAP_EVENT_4", displayName: "eCAP event 4" },
]
let ECAP_SyncOutMode = [
	{ name: "ECAP_SYNC_OUT_SYNCI", displayName: "SYNC OUT SYNCI" },
	{ name: "ECAP_SYNC_OUT_COUNTER_PRD", displayName: "SYNC OUT COUNTER PRD" },
	{ name: "ECAP_SYNC_OUT_DISABLED", displayName: "SYNC OUT DISABLED" },
]
let ECAP_APWMPolarity = [
	{ name: "ECAP_APWM_ACTIVE_HIGH", displayName: "APWM is active high" },
	{ name: "ECAP_APWM_ACTIVE_LOW", displayName: "APWM is active low" },
]
let ECAP_EventPolarity = [
	{ name: "ECAP_EVNT_RISING_EDGE", displayName: "Rising edge polarity" },
	{ name: "ECAP_EVNT_FALLING_EDGE", displayName: "Falling edge polarity" },
]
let ECAP_InputCaptureSignals = [
	{ name: "ECAP_INPUT_INPUTXBAR1", displayName: "INPUT INPUTXBAR1" },
	{ name: "ECAP_INPUT_INPUTXBAR2", displayName: "INPUT INPUTXBAR2" },
	{ name: "ECAP_INPUT_INPUTXBAR3", displayName: "INPUT INPUTXBAR3" },
	{ name: "ECAP_INPUT_INPUTXBAR4", displayName: "INPUT INPUTXBAR4" },
	{ name: "ECAP_INPUT_INPUTXBAR5", displayName: "INPUT INPUTXBAR5" },
	{ name: "ECAP_INPUT_INPUTXBAR6", displayName: "INPUT INPUTXBAR6" },
	{ name: "ECAP_INPUT_INPUTXBAR7", displayName: "INPUT INPUTXBAR7" },
	{ name: "ECAP_INPUT_INPUTXBAR8", displayName: "INPUT INPUTXBAR8" },
	{ name: "ECAP_INPUT_INPUTXBAR9", displayName: "INPUT INPUTXBAR9" },
	{ name: "ECAP_INPUT_INPUTXBAR10", displayName: "INPUT INPUTXBAR10" },
	{ name: "ECAP_INPUT_INPUTXBAR11", displayName: "INPUT INPUTXBAR11" },
	{ name: "ECAP_INPUT_INPUTXBAR12", displayName: "INPUT INPUTXBAR12" },
	{ name: "ECAP_INPUT_INPUTXBAR13", displayName: "INPUT INPUTXBAR13" },
	{ name: "ECAP_INPUT_INPUTXBAR14", displayName: "INPUT INPUTXBAR14" },
	{ name: "ECAP_INPUT_INPUTXBAR15", displayName: "INPUT INPUTXBAR15" },
	{ name: "ECAP_INPUT_INPUTXBAR16", displayName: "INPUT INPUTXBAR16" },
	{ name: "ECAP_INPUT_CANA_INT0", displayName: "INPUT CANA INT0" },
	{ name: "ECAP_INPUT_CANB_INT0", displayName: "INPUT CANB INT0" },
	{ name: "ECAP_INPUT_ECAP_DELAY_CLOCK", displayName: "INPUT ECAP DELAY CLOCK" },
	{ name: "ECAP_INPUT_OUTPUTXBAR1", displayName: "INPUT OUTPUTXBAR1" },
	{ name: "ECAP_INPUT_OUTPUTXBAR2", displayName: "INPUT OUTPUTXBAR2" },
	{ name: "ECAP_INPUT_OUTPUTXBAR3", displayName: "INPUT OUTPUTXBAR3" },
	{ name: "ECAP_INPUT_OUTPUTXBAR4", displayName: "INPUT OUTPUTXBAR4" },
	{ name: "ECAP_INPUT_OUTPUTXBAR5", displayName: "INPUT OUTPUTXBAR5" },
	{ name: "ECAP_INPUT_OUTPUTXBAR6", displayName: "INPUT OUTPUTXBAR6" },
	{ name: "ECAP_INPUT_OUTPUTXBAR7", displayName: "INPUT OUTPUTXBAR7" },
	{ name: "ECAP_INPUT_OUTPUTXBAR8", displayName: "INPUT OUTPUTXBAR8" },
	{ name: "ECAP_INPUT_ADC_C_EVENT4", displayName: "INPUT ADC C EVENT4" },
	{ name: "ECAP_INPUT_ADC_C_EVENT3", displayName: "INPUT ADC C EVENT3" },
	{ name: "ECAP_INPUT_ADC_C_EVENT2", displayName: "INPUT ADC C EVENT2" },
	{ name: "ECAP_INPUT_ADC_C_EVENT1", displayName: "INPUT ADC C EVENT1" },
	{ name: "ECAP_INPUT_ADC_B_EVENT4", displayName: "INPUT ADC B EVENT4" },
	{ name: "ECAP_INPUT_ADC_B_EVENT3", displayName: "INPUT ADC B EVENT3" },
	{ name: "ECAP_INPUT_ADC_B_EVENT2", displayName: "INPUT ADC B EVENT2" },
	{ name: "ECAP_INPUT_ADC_B_EVENT1", displayName: "INPUT ADC B EVENT1" },
	{ name: "ECAP_INPUT_ADC_A_EVENT4", displayName: "INPUT ADC A EVENT4" },
	{ name: "ECAP_INPUT_ADC_A_EVENT3", displayName: "INPUT ADC A EVENT3" },
	{ name: "ECAP_INPUT_ADC_A_EVENT2", displayName: "INPUT ADC A EVENT2" },
	{ name: "ECAP_INPUT_ADC_A_EVENT1", displayName: "INPUT ADC A EVENT1" },
	{ name: "ECAP_INPUT_SDFM1_FLT1_COMPARE_LOW", displayName: "INPUT SDFM1 FLT1 COMPARE LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT2_COMPARE_LOW", displayName: "INPUT SDFM1 FLT2 COMPARE LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT3_COMPARE_LOW", displayName: "INPUT SDFM1 FLT3 COMPARE LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT4_COMPARE_LOW", displayName: "INPUT SDFM1 FLT4 COMPARE LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT1_COMPARE_HIGH", displayName: "INPUT SDFM1 FLT1 COMPARE HIGH" },
	{ name: "ECAP_INPUT_SDFM1_FLT2_COMPARE_HIGH", displayName: "INPUT SDFM1 FLT2 COMPARE HIGH" },
	{ name: "ECAP_INPUT_SDFM1_FLT3_COMPARE_HIGH", displayName: "INPUT SDFM1 FLT3 COMPARE HIGH" },
	{ name: "ECAP_INPUT_SDFM1_FLT4_COMPARE_HIGH", displayName: "INPUT SDFM1 FLT4 COMPARE HIGH" },
	{ name: "ECAP_INPUT_SDFM1_FLT1_COMPARE_HIGH_OR_LOW", displayName: "INPUT SDFM1 FLT1 COMPARE HIGH OR LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT2_COMPARE_HIGH_OR_LOW", displayName: "INPUT SDFM1 FLT2 COMPARE HIGH OR LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT3_COMPARE_HIGH_OR_LOW", displayName: "INPUT SDFM1 FLT3 COMPARE HIGH OR LOW" },
	{ name: "ECAP_INPUT_SDFM1_FLT4_COMPARE_HIGH_OR_LOW", displayName: "INPUT SDFM1 FLT4 COMPARE HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS1_CTRIP_LOW", displayName: "INPUT CMPSS1 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS2_CTRIP_LOW", displayName: "INPUT CMPSS2 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS3_CTRIP_LOW", displayName: "INPUT CMPSS3 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS4_CTRIP_LOW", displayName: "INPUT CMPSS4 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS5_CTRIP_LOW", displayName: "INPUT CMPSS5 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS6_CTRIP_LOW", displayName: "INPUT CMPSS6 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS7_CTRIP_LOW", displayName: "INPUT CMPSS7 CTRIP LOW" },
	{ name: "ECAP_INPUT_CMPSS1_CTRIP_HIGH", displayName: "INPUT CMPSS1 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS2_CTRIP_HIGH", displayName: "INPUT CMPSS2 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS3_CTRIP_HIGH", displayName: "INPUT CMPSS3 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS4_CTRIP_HIGH", displayName: "INPUT CMPSS4 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS5_CTRIP_HIGH", displayName: "INPUT CMPSS5 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS6_CTRIP_HIGH", displayName: "INPUT CMPSS6 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS7_CTRIP_HIGH", displayName: "INPUT CMPSS7 CTRIP HIGH" },
	{ name: "ECAP_INPUT_CMPSS1_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS1 CTRIP HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS2_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS2 CTRIP HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS3_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS3 CTRIP HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS4_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS4 CTRIP HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS5_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS5 CTRIP HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS6_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS6 CTRIP HIGH OR LOW" },
	{ name: "ECAP_INPUT_CMPSS7_CTRIP_HIGH_OR_LOW", displayName: "INPUT CMPSS7 CTRIP HIGH OR LOW" },
]
exports = {
	ECAP_EmulationMode: ECAP_EmulationMode,
	ECAP_CaptureMode: ECAP_CaptureMode,
	ECAP_Events: ECAP_Events,
	ECAP_SyncOutMode: ECAP_SyncOutMode,
	ECAP_APWMPolarity: ECAP_APWMPolarity,
	ECAP_EventPolarity: ECAP_EventPolarity,
	ECAP_InputCaptureSignals: ECAP_InputCaptureSignals,
}
