example1_stb.h File Reference
example1_stb.h File Reference
#include <stdint.h>
#include <math.h>
#include "sfra_examples_settings.h"
#include "sfra_examples_hal.h"
#include "DCLF32.h"
#include "sfra_f32.h"
#include "sfra_gui_scicomms_driverlib.h"
Functions
void setupSFRA ()
void globalVariablesInit ()
static void controlCode (void)
Variables
DCL_PI gi
volatile float32_t gi_out
volatile float32_t gi_out_prev
volatile float32_t ac_cur_ref
volatile int32_t closeGiLoop
Function Documentation
setupSFRA()
void setupSFRA ()
globalVariablesInit()
void globalVariablesInit ()
controlCode()
static void controlCode (void) inline static
References ac_cur_ref, C28x_CONTROLISR_INTERRUPT_TRIG_PWM_BASE, clearPWMInterruptFlag(), closeGiLoop, gi, gi_out, gi_out_prev, resetProfilingGPIO(), setProfilingGPIO(), SFRA_F32_collect, and SFRA_F32_inject.
Variable Documentation
gi
DCL_PI gi
Referenced by controlCode().
gi_out
volatile float32_t gi_out
Referenced by controlCode().
gi_out_prev
volatile float32_t gi_out_prev
Referenced by controlCode().
ac_cur_ref
volatile float32_t ac_cur_ref
Referenced by controlCode().
closeGiLoop
volatile int32_t closeGiLoop
Referenced by controlCode().
Copyright 2021, Texas Instruments Incorporated