fcl_foc_cpu_dm.h File Reference
fcl_foc_cpu_dm.h File Reference
#include <math.h>
#include "stdbool.h"
#include "stdint.h"
#include "F28x_Project.h"
#include "device.h"
#include "f28x_bmsk.h"
#include "fcl_enum.h"
#include "fcl_cmplx_ctrl.h"
#include "qep_defs.h"
#include "epwm.h"
#include "eqep.h"
#include "rampgen.h"
#include "rmp_cntl.h"
#include "ipark.h"
#include "clarke.h"
#include "park.h"
#include "speed_fr.h"
#include "svgen.h"
#include "pi.h"
#include "pid_grando.h"
#include "speed_observer.h"
#include "DCLF32.h"
#include "DCL_NLPID.h"
#include "dual_axis_servo_drive_settings.h"
#include "dual_axis_servo_drive_user.h"
#include "dual_axis_servo_drive_hal.h"
Data Structures
struct _FCL_Parameters_t_
typedefs for motorVars
struct _MOTOR_Vars_t_
typedefs for motorVars
Macros
#define PI 3.14159265358979
#define BITFIELD_MODE 0
#define DRIVERLIB_MODE 1
#define DRIVER_MODULE DRIVERLIB_MODE
#define FCL_PARS_DEFAULTS
#define EQEP_POSCNT_INIT_NOTHING 0U
No action.
#define EQEP_POSCNT_INIT_RISING_EDGE 0x0200U
poscnt=posinit @ QEPI rise
#define EQEP_POSCNT_INIT_FALLING_EDGE 0x0300U
poscnt=posinit @ QEPI fall
Typedefs
typedef struct _FCL_Parameters_t_ FCL_Parameters_t
typedefs for motorVars
typedef struct _MOTOR_Vars_t_ MOTOR_Vars_t
typedefs for motorVars
Functions
uint32_t FCL_getSwVersion (void)
void FCL_initPWM (MOTOR_Vars_t *pMotor, const uint32_t pwmBaseU, const uint32_t pwmBaseV, const uint32_t pwmBaseW)
void FCL_initQEP (MOTOR_Vars_t *pMotor, const uint32_t qepBaseA)
void FCL_initADC_2In (MOTOR_Vars_t *pMotor, uint32_t adcBaseW, const uint32_t adcResultBaseV, ADC_PPBNumber adcV_PPBNum, const uint32_t adcResultBaseW, ADC_PPBNumber adcW_PPBNum)
void FCL_initADC_3In (MOTOR_Vars_t *pMotor, uint32_t adcBaseW, const uint32_t adcResultBaseU, ADC_PPBNumber adcU_PPBNum, const uint32_t adcResultBaseV, ADC_PPBNumber adcV_PPBNum, const uint32_t adcResultBaseW, ADC_PPBNumber adcW_PPBNum)
static void FCL_readCount (MOTOR_Vars_t *pMotor)
static void FCL_resetController (MOTOR_Vars_t *pMotor)
static void FCL_runPI (FCL_cmplxCtrl_t *pPI)
static void FCL_runCCSyn (FCL_cmplxCtrl_t *pId, FCL_cmplxCtrl_t *pIq)
static void FCL_runPICtrl (MOTOR_Vars_t *pMotor)
static void FCL_runPICtrlWrap (MOTOR_Vars_t *pMotor)
static void FCL_runComplexCtrl (MOTOR_Vars_t *pMotor)
static void FCL_runComplexCtrlWrap (MOTOR_Vars_t *pMotor)
static void EQEP_resetPoscnt (uint32_t base, uint16_t initMode)
static void FCL_runQEPPosEst (MOTOR_Vars_t *pMotor)
static void FCL_runQEPPosEstWrap (MOTOR_Vars_t *pMotor)
Variables
MOTOR_Vars_t motorVars [2]
Macro Definition Documentation
PI
#define PI 3.14159265358979
BITFIELD_MODE
#define BITFIELD_MODE 0
DRIVERLIB_MODE
#define DRIVERLIB_MODE 1
DRIVER_MODULE
#define DRIVER_MODULE DRIVERLIB_MODE
FCL_PARS_DEFAULTS
#define FCL_PARS_DEFAULTS
Value:
{                                                    \
    0, /* carrierMid */                                                        \
    0, /* adcScale */                                                          \
    0, /* cmidsqrt3 */                                                         \
    0, /* tSamp */                                                             \
    0, /* Rd */                                                                \
    0, /* Rq */                                                                \
    0, /* Ld */                                                                \
    0, /* Lq */                                                                \
    0, /* Vbase */                                                             \
    0, /* Ibase */                                                             \
    0, /* wccD */                                                              \
    0, /* wccQ */                                                              \
    0, /* Vdcbus */                                                            \
    0, /* BemfK */                                                             \
    0  /* Wbase */                                                             \
}
EQEP_POSCNT_INIT_NOTHING
#define EQEP_POSCNT_INIT_NOTHING 0U
No action.
EQEP_POSCNT_INIT_RISING_EDGE
#define EQEP_POSCNT_INIT_RISING_EDGE 0x0200U
poscnt=posinit @ QEPI rise
EQEP_POSCNT_INIT_FALLING_EDGE
#define EQEP_POSCNT_INIT_FALLING_EDGE 0x0300U
poscnt=posinit @ QEPI fall
Typedef Documentation
FCL_Parameters_t
typedef struct _FCL_Parameters_t_ FCL_Parameters_t
typedefs for motorVars
MOTOR_Vars_t
typedef struct _MOTOR_Vars_t_ MOTOR_Vars_t
typedefs for motorVars
Function Documentation
FCL_getSwVersion()
uint32_t FCL_getSwVersion (void)
FCL_initPWM()
void FCL_initPWM (MOTOR_Vars_t * pMotor, const uint32_t pwmBaseU, const uint32_t pwmBaseV, const uint32_t pwmBaseW)
FCL_initQEP()
void FCL_initQEP (MOTOR_Vars_t * pMotor, const uint32_t qepBaseA)
FCL_initADC_2In()
void FCL_initADC_2In (MOTOR_Vars_t * pMotor, uint32_t adcBaseW, const uint32_t adcResultBaseV, ADC_PPBNumber adcV_PPBNum, const uint32_t adcResultBaseW, ADC_PPBNumber adcW_PPBNum)
FCL_initADC_3In()
void FCL_initADC_3In (MOTOR_Vars_t * pMotor, uint32_t adcBaseW, const uint32_t adcResultBaseU, ADC_PPBNumber adcU_PPBNum, const uint32_t adcResultBaseV, ADC_PPBNumber adcV_PPBNum, const uint32_t adcResultBaseW, ADC_PPBNumber adcW_PPBNum)
FCL_readCount()
static void FCL_readCount (MOTOR_Vars_t * pMotor) inline static
References _MOTOR_Vars_t_::fclCycleCount, and _MOTOR_Vars_t_::pwmBaseU.
Referenced by FCL_runComplexCtrl(), and FCL_runPICtrl().
FCL_resetController()
static void FCL_resetController (MOTOR_Vars_t * pMotor) inline static
References FCL_cmplxCtrl_t::carryOver, _MOTOR_Vars_t_::cmplx_Id, _MOTOR_Vars_t_::cmplx_Iq, FCL_cmplxCtrl_t::err, FCL_cmplxCtrl_t::out, FCL_cmplxCtrl_t::ref, _MOTOR_Vars_t_::speedWePrev, and FCL_cmplxCtrl_t::xErr.
FCL_runPI()
static void FCL_runPI (FCL_cmplxCtrl_t * pPI) inline static
References FCL_cmplxCtrl_t::carryOver, FCL_cmplxCtrl_t::err, FCL_cmplxCtrl_t::Kerr, FCL_cmplxCtrl_t::out, FCL_cmplxCtrl_t::Umax, and FCL_cmplxCtrl_t::Umin.
Referenced by FCL_runPICtrl().
FCL_runCCSyn()
static void FCL_runCCSyn (FCL_cmplxCtrl_t * pId, FCL_cmplxCtrl_t * pIq) inline static
References FCL_cmplxCtrl_t::carryOver, FCL_cmplxCtrl_t::cosWTs, FCL_cmplxCtrl_t::err, FCL_cmplxCtrl_t::kDirect, FCL_cmplxCtrl_t::out, FCL_cmplxCtrl_t::sinWTs, FCL_cmplxCtrl_t::Umax, and FCL_cmplxCtrl_t::Umin.
Referenced by FCL_runComplexCtrl().
FCL_runPICtrl()
static void FCL_runPICtrl (MOTOR_Vars_t * pMotor) inline static
References _MOTOR_Vars_t_::adcBaseW, _MOTOR_Vars_t_::adcIntNumber, _FCL_Parameters_::carrierMid, _FCL_Parameters_::cmidsqrt3, _MOTOR_Vars_t_::cmplx_Id, _MOTOR_Vars_t_::cmplx_Iq, _MOTOR_Vars_t_::curA_PPBRESULT, _MOTOR_Vars_t_::curB_PPBRESULT, FCL_cmplxCtrl_t::err, _MOTOR_Vars_t_::FCL_params, FCL_readCount(), FCL_runPI(), FCL_cmplxCtrl_t::out, _MOTOR_Vars_t_::pADCIntFlag, _MOTOR_Vars_t_::pangle, _MOTOR_Vars_t_::pwmCompA, _MOTOR_Vars_t_::pwmCompB, _MOTOR_Vars_t_::pwmCompC, and FCL_cmplxCtrl_t::ref.
FCL_runPICtrlWrap()
static void FCL_runPICtrlWrap (MOTOR_Vars_t * pMotor) inline static
References _FCL_Parameters_::BemfK, FCL_cmplxCtrl_t::carryOver, _MOTOR_Vars_t_::cmplx_Id, _MOTOR_Vars_t_::cmplx_Iq, FCL_cmplxCtrl_t::err, FCL_cmplxCtrl_t::fbk, _MOTOR_Vars_t_::FCL_params, _FCL_Parameters_::Ibase, FCL_cmplxCtrl_t::Kerr, FCL_cmplxCtrl_t::KerrOld, FCL_cmplxCtrl_t::Ki, FCL_cmplxCtrl_t::Kp, _FCL_Parameters_::Ld, _FCL_Parameters_::Lq, _FCL_Parameters_::Rd, FCL_cmplxCtrl_t::ref, _FCL_Parameters_::Rq, _MOTOR_Vars_t_::speedWe, _MOTOR_Vars_t_::speedWePrev, _FCL_Parameters_::tSamp, _FCL_Parameters_::Vdcbus, _FCL_Parameters_::wccD, and _FCL_Parameters_::wccQ.
FCL_runComplexCtrl()
static void FCL_runComplexCtrl (MOTOR_Vars_t * pMotor) inline static
References _MOTOR_Vars_t_::adcBaseW, _MOTOR_Vars_t_::adcIntNumber, _FCL_Parameters_::carrierMid, _FCL_Parameters_::cmidsqrt3, _MOTOR_Vars_t_::cmplx_Id, _MOTOR_Vars_t_::cmplx_Iq, _MOTOR_Vars_t_::curA_PPBRESULT, _MOTOR_Vars_t_::curB_PPBRESULT, FCL_cmplxCtrl_t::err, _MOTOR_Vars_t_::FCL_params, FCL_readCount(), FCL_runCCSyn(), FCL_cmplxCtrl_t::out, _MOTOR_Vars_t_::pADCIntFlag, _MOTOR_Vars_t_::pangle, _MOTOR_Vars_t_::pwmCompA, _MOTOR_Vars_t_::pwmCompB, _MOTOR_Vars_t_::pwmCompC, and FCL_cmplxCtrl_t::ref.
FCL_runComplexCtrlWrap()
static void FCL_runComplexCtrlWrap (MOTOR_Vars_t * pMotor) inline static
References _FCL_Parameters_::BemfK, FCL_cmplxCtrl_t::carryOver, _MOTOR_Vars_t_::cmplx_Id, _MOTOR_Vars_t_::cmplx_Iq, FCL_cmplxCtrl_t::cosWTs, FCL_cmplxCtrl_t::err, FCL_cmplxCtrl_t::expVal, FCL_cmplxCtrl_t::fbk, _MOTOR_Vars_t_::FCL_params, _FCL_Parameters_::Ibase, FCL_cmplxCtrl_t::kDirect, _FCL_Parameters_::Ld, _FCL_Parameters_::Lq, _FCL_Parameters_::Rd, FCL_cmplxCtrl_t::ref, _FCL_Parameters_::Rq, FCL_cmplxCtrl_t::sinWTs, _MOTOR_Vars_t_::speedWe, _MOTOR_Vars_t_::speedWePrev, _FCL_Parameters_::tSamp, _FCL_Parameters_::Vdcbus, _FCL_Parameters_::Wbase, _FCL_Parameters_::wccD, and _FCL_Parameters_::wccQ.
EQEP_resetPoscnt()
static void EQEP_resetPoscnt (uint32_t base, uint16_t initMode) inline static
Referenced by FCL_runQEPPosEst().
FCL_runQEPPosEst()
static void FCL_runQEPPosEst (MOTOR_Vars_t * pMotor) inline static
References ENC_CALIBRATION_DONE, ENC_WAIT_FOR_INDEX, EQEP_POSCNT_INIT_NOTHING, EQEP_POSCNT_INIT_RISING_EDGE, EQEP_resetPoscnt(), _MOTOR_Vars_t_::lsw, _MOTOR_Vars_t_::pangle, _MOTOR_Vars_t_::polePairs, _MOTOR_Vars_t_::posElecTheta, _MOTOR_Vars_t_::posMechScaler, _MOTOR_Vars_t_::posMechTheta, _MOTOR_Vars_t_::pQEPRegs, and _MOTOR_Vars_t_::rg.
FCL_runQEPPosEstWrap()
static void FCL_runQEPPosEstWrap (MOTOR_Vars_t * pMotor) inline static
References ENC_ALIGNMENT, _MOTOR_Vars_t_::lsw, and _MOTOR_Vars_t_::pQEPRegs.
Variable Documentation
motorVars
MOTOR_Vars_t motorVars[2]
Copyright 2021, Texas Instruments Incorporated