FWC
FWC
Data Structures
struct _FWC_Obj_
Defines the Field Weakening Control (FWC) object.
Typedefs
typedef struct _FWC_Obj_ FWC_Obj
Defines the Field Weakening Control (FWC) object.
typedef struct _FWC_Obj_ * FWC_Handle
Defines the FWC handle.
Functions
static void FWC_disable (FWC_Handle handle)
Disables the FWC function.
static void FWC_enable (FWC_Handle handle)
Enables the FWC function.
static float32_t * FWC_getCurrentAngle_rad_addr (FWC_Handle handle)
Gets the stator current phase angle memory address.
static float32_t FWC_getCurrentAngle_rad (FWC_Handle handle)
Gets the stator current phase angle value (angleCurrent_rad)
static bool FWC_getFlagEnable (FWC_Handle handle)
Gets the enable controller flag value from the FWC.
static void FWC_setCurrentAngle_rad (FWC_Handle handle, const float32_t angleCurrent_rad)
Sets the stator current phase angle value.
static void FWC_setFlagEnable (FWC_Handle handle, const bool flagEnable)
Sets the enable flag.
static void FWC_setKi (FWC_Handle handle, const float32_t Ki)
Sets the integral gain (Ki) value.
static void FWC_setKp (FWC_Handle handle, const float32_t Kp)
Sets the proportional gain (Kp) value.
static void FWC_setGains (FWC_Handle handle, const float32_t Kp, const float32_t Ki)
Sets the gain values.
static void FWC_setAngleMinMax (FWC_Handle handle, const float32_t angleMin_rad, const float32_t angleMax_rad)
Sets the minimum and maximum output values of FWC.
static void FWC_setAngleMax (FWC_Handle handle, const float32_t angleMax_rad)
Sets the maximum output values of FWC.
static void FWC_resetUi (FWC_Handle handle)
Resets the integrator start value (Ui)
static void FWC_setUi (FWC_Handle handle, const float32_t Ui)
Sets the integrator start value (Ui)
FWC_Handle FWC_init (void *pMemory, const size_t numBytes)
Initializes the Field Weakening Control (FWC) module.
FWC_Handle cla_FWC_init (void *pMemory, const size_t numBytes)
void FWC_setParams (FWC_Handle handle, const float32_t Kp, const float32_t Ki, const float32_t angleMin_rad, const float32_t angleMax_rad)
Sets the Field Weakening Control (FWC) module parmaeters.
static void FWC_computeCurrentAngle (FWC_Handle handle, const float32_t Vs_V, const float32_t VsRef_V)
Runs the Field Weakening Control (FWC)
Detailed Description
Typedef Documentation
FWC_Obj
typedef struct _FWC_Obj_ FWC_Obj
Defines the Field Weakening Control (FWC) object.
FWC_Handle
typedef struct _FWC_Obj_* FWC_Handle
Defines the FWC handle.
Function Documentation
FWC_disable()
static void FWC_disable (FWC_Handle handle) inline static
Disables the FWC function.
Parameters
[in] handle The Field Weakening Control (FWC) handle
References _FWC_Obj_::flagEnable.
FWC_enable()
static void FWC_enable (FWC_Handle handle) inline static
Enables the FWC function.
Parameters
[in] handle The Field Weakening Control (FWC) handle
References _FWC_Obj_::flagEnable.
FWC_getCurrentAngle_rad_addr()
static float32_t* FWC_getCurrentAngle_rad_addr (FWC_Handle handle) inline static
Gets the stator current phase angle memory address.
Parameters
[in] handle The Field Weakening Control (FWC) handle
Returns
The stator current phase angle memory address
References _FWC_Obj_::angleCurrent_rad.
FWC_getCurrentAngle_rad()
static float32_t FWC_getCurrentAngle_rad (FWC_Handle handle) inline static
Gets the stator current phase angle value (angleCurrent_rad)
Parameters
[in] handle The Field Weakening Control (FWC) handle
Returns
The stator current phase angle value, rad
References _FWC_Obj_::angleCurrent_rad.
FWC_getFlagEnable()
static bool FWC_getFlagEnable (FWC_Handle handle) inline static
Gets the enable controller flag value from the FWC.
Parameters
[in] handle The Field Weakening Control (FWC) handle
Returns
The enable FWC flag value
References _FWC_Obj_::flagEnable.
Referenced by FWC_computeCurrentAngle().
FWC_setCurrentAngle_rad()
static void FWC_setCurrentAngle_rad (FWC_Handle handle, const float32_t angleCurrent_rad) inline static
Sets the stator current phase angle value.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] angleCurrent_rad The stator current phase angle value, rad
References _FWC_Obj_::angleCurrent_rad.
FWC_setFlagEnable()
static void FWC_setFlagEnable (FWC_Handle handle, const bool flagEnable) inline static
Sets the enable flag.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] flagEnable The enable flag
References _FWC_Obj_::flagEnable.
FWC_setKi()
static void FWC_setKi (FWC_Handle handle, const float32_t Ki) inline static
Sets the integral gain (Ki) value.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] Ki The Ki value
References PI_setKi(), and _FWC_Obj_::piHandle.
FWC_setKp()
static void FWC_setKp (FWC_Handle handle, const float32_t Kp) inline static
Sets the proportional gain (Kp) value.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] Kp The Kp value
References PI_setKp(), and _FWC_Obj_::piHandle.
FWC_setGains()
static void FWC_setGains (FWC_Handle handle, const float32_t Kp, const float32_t Ki) inline static
Sets the gain values.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] Kp The Kp gain value
[in] Ki The Ki gain value
References PI_setKi(), PI_setKp(), and _FWC_Obj_::piHandle.
FWC_setAngleMinMax()
static void FWC_setAngleMinMax (FWC_Handle handle, const float32_t angleMin_rad, const float32_t angleMax_rad) inline static
Sets the minimum and maximum output values of FWC.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] angleMin_rad The angle out minimum value
[in] angleMax_rad The angle out maximum value
References PI_setMinMax(), and _FWC_Obj_::piHandle.
FWC_setAngleMax()
static void FWC_setAngleMax (FWC_Handle handle, const float32_t angleMax_rad) inline static
Sets the maximum output values of FWC.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] angleMax_rad The angle out maximum value
References PI_setOutMin(), and _FWC_Obj_::piHandle.
FWC_resetUi()
static void FWC_resetUi (FWC_Handle handle) inline static
Resets the integrator start value (Ui)
Parameters
[in] handle The Field Weakening Control (FWC) handle
References PI_setUi(), and _FWC_Obj_::piHandle.
FWC_setUi()
static void FWC_setUi (FWC_Handle handle, const float32_t Ui) inline static
Sets the integrator start value (Ui)
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] Ui The integrator start value
References PI_setUi(), and _FWC_Obj_::piHandle.
FWC_init()
FWC_Handle FWC_init (void * pMemory, const size_t numBytes)
Initializes the Field Weakening Control (FWC) module.
Parameters
[in] pMemory A pointer to the memory for the FWC object
[in] numBytes The number of bytes allocated for the FWC object
Returns
The Field Weakening Control (FWC) object handle
cla_FWC_init()
FWC_Handle cla_FWC_init (void * pMemory, const size_t numBytes)
FWC_setParams()
void FWC_setParams (FWC_Handle handle, const float32_t Kp, const float32_t Ki, const float32_t angleMin_rad, const float32_t angleMax_rad)
Sets the Field Weakening Control (FWC) module parmaeters.
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] Kp The Kp gain value
[in] Ki The Ki gain value
[in] angleMin_rad The angle out minimum value
[in] angleMax_rad The angle out maximum value
FWC_computeCurrentAngle()
static void FWC_computeCurrentAngle (FWC_Handle handle, const float32_t Vs_V, const float32_t VsRef_V) inline static
Runs the Field Weakening Control (FWC)
Parameters
[in] handle The Field Weakening Control (FWC) handle
[in] Vs_V The output voltage vector, V
[in] VsRef_V The reference voltage vector, V
Returns
None
References _FWC_Obj_::angleCurrent_rad, FWC_getFlagEnable(), MATH_PI_OVER_TWO, PI_run_series(), and _FWC_Obj_::piHandle.
Copyright 2021, Texas Instruments Incorporated