FILTER_FO
FILTER_FO
Data Structures
struct _FILTER_FO_Obj_
Defines the first-order filter (FILTER_FO) object.
Typedefs
typedef struct _FILTER_FO_Obj_ FILTER_FO_Obj
Defines the first-order filter (FILTER_FO) object.
typedef struct _FILTER_FO_Obj_ * FILTER_FO_Handle
Defines the first-order filter (FILTER_FO) handle.
Functions
static float32_t FILTER_FO_get_a1 (FILTER_FO_Handle handle)
Gets the first-order filter denominator coefficient a1.
static float32_t FILTER_FO_get_b0 (FILTER_FO_Handle handle)
Gets the first-order filter numerator coefficient b0.
static float32_t FILTER_FO_get_b1 (FILTER_FO_Handle handle)
Gets the first-order filter numerator coefficient b1.
static float32_t FILTER_FO_get_x1 (FILTER_FO_Handle handle)
Gets the first-order filter input value at time sample n=-1.
static float32_t FILTER_FO_get_y1 (FILTER_FO_Handle handle)
Gets the first-order filter output value at time sample n=-1.
void FILTER_FO_getDenCoeffs (FILTER_FO_Handle handle, float32_t *pa1)
Gets the first-order filter denominator coefficients.
void FILTER_FO_getInitialConditions (FILTER_FO_Handle handle, float32_t *px1, float32_t *py1)
Gets the initial conditions of the first-order filter.
void FILTER_FO_getNumCoeffs (FILTER_FO_Handle handle, float32_t *pb0, float32_t *pb1)
Gets the first-order filter numerator coefficients.
FILTER_FO_Handle FILTER_FO_init (void *pMemory, const size_t numBytes)
Initializes the first-order filter.
static float32_t FILTER_FO_run (FILTER_FO_Handle handle, const float32_t inputValue)
Runs a first-order filter of the form y[n] = b0*x[n] + b1*x[n-1] - a1*y[n-1].
static float32_t FILTER_FO_run_form_0 (FILTER_FO_Handle handle, const float32_t inputValue)
Runs a first-order filter of the form y[n] = b0*x[n] - a1*y[n-1].
static void FILTER_FO_set_a1 (FILTER_FO_Handle handle, const float32_t a1)
Sets the first-order filter denominator coefficient a1.
static void FILTER_FO_set_b0 (FILTER_FO_Handle handle, const float32_t b0)
Sets the first-order filter numerator coefficient b0.
static void FILTER_FO_set_b1 (FILTER_FO_Handle handle, const float32_t b1)
Sets the first-order filter numerator coefficient b1.
static void FILTER_FO_set_x1 (FILTER_FO_Handle handle, const float32_t x1)
Sets the first-order filter input value at time sample n=-1.
static void FILTER_FO_set_y1 (FILTER_FO_Handle handle, const float32_t y1)
Sets the first-order filter output value at time sample n=-1.
void FILTER_FO_setDenCoeffs (FILTER_FO_Handle handle, const float32_t a1)
Sets the first-order filter denominator coefficients.
void FILTER_FO_setInitialConditions (FILTER_FO_Handle handle, const float32_t x1, const float32_t y1)
Sets the initial conditions of the first-order filter.
void FILTER_FO_setNumCoeffs (FILTER_FO_Handle handle, const float32_t b0, const float32_t b1)
Sets the first-order filter numerator coefficients.
Detailed Description
Typedef Documentation
FILTER_FO_Obj
typedef struct _FILTER_FO_Obj_ FILTER_FO_Obj
Defines the first-order filter (FILTER_FO) object.
FILTER_FO_Handle
typedef struct _FILTER_FO_Obj_* FILTER_FO_Handle
Defines the first-order filter (FILTER_FO) handle.
Function Documentation
FILTER_FO_get_a1()
static float32_t FILTER_FO_get_a1 (FILTER_FO_Handle handle) inline static
Gets the first-order filter denominator coefficient a1.
Parameters
[in] handle The filter handle
Returns
The filter coefficient value for z^(-1)
References _FILTER_FO_Obj_::a1.
FILTER_FO_get_b0()
static float32_t FILTER_FO_get_b0 (FILTER_FO_Handle handle) inline static
Gets the first-order filter numerator coefficient b0.
Parameters
[in] handle The filter handle
Returns
The filter coefficient value for z^0
References _FILTER_FO_Obj_::b0.
FILTER_FO_get_b1()
static float32_t FILTER_FO_get_b1 (FILTER_FO_Handle handle) inline static
Gets the first-order filter numerator coefficient b1.
Parameters
[in] handle The filter handle
Returns
The filter coefficient value for z^(-1)
References _FILTER_FO_Obj_::b1.
FILTER_FO_get_x1()
static float32_t FILTER_FO_get_x1 (FILTER_FO_Handle handle) inline static
Gets the first-order filter input value at time sample n=-1.
Parameters
[in] handle The filter handle
Returns
The input value at time sample n=-1
References _FILTER_FO_Obj_::x1.
FILTER_FO_get_y1()
static float32_t FILTER_FO_get_y1 (FILTER_FO_Handle handle) inline static
Gets the first-order filter output value at time sample n=-1.
Parameters
[in] handle The filter handle
Returns
The output value at time sample n=-1
References _FILTER_FO_Obj_::y1.
FILTER_FO_getDenCoeffs()
void FILTER_FO_getDenCoeffs (FILTER_FO_Handle handle, float32_t * pa1)
Gets the first-order filter denominator coefficients.
Parameters
[in] handle The filter handle
[in] pa1 The pointer to memory for the filter coefficient value for z^(-1)
Returns
None
FILTER_FO_getInitialConditions()
void FILTER_FO_getInitialConditions (FILTER_FO_Handle handle, float32_t * px1, float32_t * py1)
Gets the initial conditions of the first-order filter.
Parameters
[in] handle The filter handle
[in] px1 The pointer to memory for the input value at time sample n=-1
[in] py1 The pointer to memory for the output value at time sample n=-1
Returns
None
FILTER_FO_getNumCoeffs()
void FILTER_FO_getNumCoeffs (FILTER_FO_Handle handle, float32_t * pb0, float32_t * pb1)
Gets the first-order filter numerator coefficients.
Parameters
[in] handle The filter handle
[in] pb0 The pointer to memory for the filter coefficient value for z^0
[in] pb1 The pointer to memory for the filter coefficient value for z^(-1)
Returns
None
FILTER_FO_init()
FILTER_FO_Handle FILTER_FO_init (void * pMemory, const size_t numBytes)
Initializes the first-order filter.
Parameters
[in] pMemory A pointer to the memory for the first-order filter object
[in] numBytes The number of bytes allocated for the first-order filter object, bytes
Returns
The filter (FILTER) object handle
FILTER_FO_run()
static float32_t FILTER_FO_run (FILTER_FO_Handle handle, const float32_t inputValue) inline static
Runs a first-order filter of the form y[n] = b0*x[n] + b1*x[n-1] - a1*y[n-1].
Parameters
[in] handle The filter handle
[in] inputValue The input value to filter
Returns
The output value from the filter
References _FILTER_FO_Obj_::a1, _FILTER_FO_Obj_::b0, _FILTER_FO_Obj_::b1, _FILTER_FO_Obj_::x1, and _FILTER_FO_Obj_::y1.
Referenced by OFFSET_run(), PID_run_parallel(), and PID_run_series().
FILTER_FO_run_form_0()
static float32_t FILTER_FO_run_form_0 (FILTER_FO_Handle handle, const float32_t inputValue) inline static
Runs a first-order filter of the form y[n] = b0*x[n] - a1*y[n-1].
Parameters
[in] handle The filter handle
[in] inputValue The input value to filter
Returns
The output value from the filter
References _FILTER_FO_Obj_::a1, _FILTER_FO_Obj_::b0, and _FILTER_FO_Obj_::y1.
FILTER_FO_set_a1()
static void FILTER_FO_set_a1 (FILTER_FO_Handle handle, const float32_t a1) inline static
Sets the first-order filter denominator coefficient a1.
Parameters
[in] handle The filter handle
[in] a1 The filter coefficient value for z^(-1)
Returns
None
References _FILTER_FO_Obj_::a1.
FILTER_FO_set_b0()
static void FILTER_FO_set_b0 (FILTER_FO_Handle handle, const float32_t b0) inline static
Sets the first-order filter numerator coefficient b0.
Parameters
[in] handle The filter handle
[in] b0 The filter coefficient value for z^0
\returnh None
References _FILTER_FO_Obj_::b0.
FILTER_FO_set_b1()
static void FILTER_FO_set_b1 (FILTER_FO_Handle handle, const float32_t b1) inline static
Sets the first-order filter numerator coefficient b1.
Parameters
[in] handle The filter handle
[in] b1 The filter coefficient value for z^(-1)
Returns
None
References _FILTER_FO_Obj_::b1.
FILTER_FO_set_x1()
static void FILTER_FO_set_x1 (FILTER_FO_Handle handle, const float32_t x1) inline static
Sets the first-order filter input value at time sample n=-1.
Parameters
[in] handle The filter handle
[in] x1 The input value at time sample n=-1
Returns
None
References _FILTER_FO_Obj_::x1.
FILTER_FO_set_y1()
static void FILTER_FO_set_y1 (FILTER_FO_Handle handle, const float32_t y1) inline static
Sets the first-order filter output value at time sample n=-1.
Parameters
[in] handle The filter handle
[in] y1 The output value at time sample n=-1
Returns
None
References _FILTER_FO_Obj_::y1.
FILTER_FO_setDenCoeffs()
void FILTER_FO_setDenCoeffs (FILTER_FO_Handle handle, const float32_t a1)
Sets the first-order filter denominator coefficients.
Parameters
[in] handle The filter handle
[in] a1 The filter coefficient value for z^(-1)
Returns
None
FILTER_FO_setInitialConditions()
void FILTER_FO_setInitialConditions (FILTER_FO_Handle handle, const float32_t x1, const float32_t y1)
Sets the initial conditions of the first-order filter.
Parameters
[in] handle The filter handle
[in] x1 The input value at time sample n=-1
[in] y1 The output value at time sample n=-1
Returns
None
FILTER_FO_setNumCoeffs()
void FILTER_FO_setNumCoeffs (FILTER_FO_Handle handle, const float32_t b0, const float32_t b1)
Sets the first-order filter numerator coefficients.
Parameters
[in] handle The filter handle
[in] b0 The filter coefficient value for z^0
[in] b1 The filter coefficient value for z^(-1)
Returns
None
Copyright 2021, Texas Instruments Incorporated