SVGEN
SVGEN
Data Structures
struct _SVGEN_Obj_
Defines the Space Vector Generator (SVGEN) object.
struct _SVGENCURRENT_Obj_
Defines the Svgen Current object.
Typedefs
typedef struct _SVGEN_Obj_ SVGEN_Obj
Defines the Space Vector Generator (SVGEN) object.
typedef struct _SVGEN_Obj_ * SVGEN_Handle
Defines the SVGEN handle.
typedef struct _SVGENCURRENT_Obj_ SVGENCURRENT_Obj
Defines the Svgen Current object.
typedef struct _SVGENCURRENT_Obj_ * SVGENCURRENT_Handle
Defines the Svgen Current handle.
Enumerations
enum SVM_Mode_e {
SVM_COM_C = 0,
SVM_MIN_C = 1,
SVM_MAX_C = 2,
SVM_DQ_S = 3
}
Enumeration for svpwm mode.
enum SVGENCURRENT_IgnoreShunt_e {
SVGENCURRENT_USE_ALL = 0,
SVGENCURRENT_IGNORE_A,
SVGENCURRENT_IGNORE_B,
SVGENCURRENT_IGNORE_C,
SVGENCURRENT_IGNORE_AB,
SVGENCURRENT_IGNORE_AC,
SVGENCURRENT_IGNORE_BC,
SVGENCURRENT_IGNORE_ALL
}
enum SVGENCURRENT_MeasureShunt_e {
SVGENCURRENT_ALL_PHASE_MEASURABLE = 1,
SVGENCURRENT_TWO_PHASE_MEASURABLE,
SVGENCURRENT_ONE_PHASE_MEASURABLE,
SVGENCURRENT_IMMEASUREABLE
}
enum SVGENCURRENT_VmidShunt_e {
SVGENCURRENT_VMID_A =0,
SVGENCURRENT_VMID_B,
SVGENCURRENT_VMID_C
}
Functions
static float32_t SVGEN_getOneOverDcBus_invV (SVGEN_Handle handle)
Gets the one over DC bus voltage value.
static SVM_Mode_e SVGEN_getMode (SVGEN_Handle handle)
Gets the spave vector mode.
static uint16_t SVGEN_getSector (SVGEN_Handle handle)
Gets the spave vector sector value.
static void SVGEN_setOneOverDcBus_invV (SVGEN_Handle handle, const float32_t oneOverDcBus_invV)
Sets the one over DC bus voltage value.
static void SVGEN_setMode (SVGEN_Handle handle, SVM_Mode_e svmMode)
Sets the spave vector mode.
static void SVGEN_setSector (SVGEN_Handle handle, uint16_t sector)
Sets the spave vector sector value.
static void SVGEN_setup (SVGEN_Handle handle, const float32_t oneOverDcBus_invV)
Sets up the space vector generator (SVGEN) module.
SVGEN_Handle SVGEN_init (void *pMemory, const size_t numBytes)
Initializes the space vector generator module.
static void SVGEN_run (SVGEN_Handle handle, const MATH_Vec2 *pVab_V, MATH_Vec3 *pVabc_pu)
Implements a SVM that saturates at the level of MaxModulation.
SVGENCURRENT_Handle SVGENCURRENT_init (void *pMemory, const size_t numBytes)
Initializes the svgen current object.
SVGENCURRENT_Handle cla_SVGENCURRENT_init (void *pMemory, const size_t numBytes)
void SVGENCURRENT_setup (SVGENCURRENT_Handle handle, const float32_t minWidth_usec, const float32_t pwmFreq_kHz, const float32_t systemFreq_MHz)
Sets up the PWM minimum width.
static void SVGENCURRENT_setMinWidth (SVGENCURRENT_Handle handle, const int16_t minwidth)
Sets the minimum Duty Cycle width that the lower switch can be on before.
static void SVGENCURRENT_setIgnoreShunt (SVGENCURRENT_Handle handle, const SVGENCURRENT_IgnoreShunt_e ignoreShunt)
Sets the ignore shunt value.
static void SVGENCURRENT_setMode (SVGENCURRENT_Handle handle, const SVGENCURRENT_MeasureShunt_e compMode)
Sets the compensation mode.
static void SVGENCURRENT_setVlimit (SVGENCURRENT_Handle handle, const float32_t Vlimit)
Sets the output voltage limit value for gurrantee a current sampling.
static SVGENCURRENT_IgnoreShunt_e SVGENCURRENT_getIgnoreShunt (SVGENCURRENT_Handle handle)
Gets the ignore shunt value.
static int16_t SVGENCURRENT_getMinWidth (SVGENCURRENT_Handle handle)
Gets the minimum Duty Cycle width that the lower switch can be on before.
static float32_t SVGENCURRENT_getVlimit (SVGENCURRENT_Handle handle)
Gets the Voltage(Duty) Limit value.
static SVGENCURRENT_MeasureShunt_e SVGENCURRENT_getMode (SVGENCURRENT_Handle handle)
Gets the current reconstruction mode.
static SVGENCURRENT_VmidShunt_e SVGENCURRENT_getVmid (SVGENCURRENT_Handle handle)
Gets the middle amplitude voltage.
static void SVGENCURRENT_RunIgnoreShunt (SVGENCURRENT_Handle handle, uint16_t cmp1, uint16_t cmp2, uint16_t cmp3, uint16_t cmpM1, uint16_t cmpM2, uint16_t cmpM3)
Gets the svgen current module ignore shunt.
static void SVGENCURRENT_RunRegenCurrent (SVGENCURRENT_Handle handle, MATH_Vec3 *pADCData, MATH_Vec3 *pADCDataPrev)
Reconstructs the missed measured currents due to a small sampling window.
static void SVGENCURRENT_compPWMData (SVGENCURRENT_Handle handle, MATH_Vec3 *pPWMData, MATH_Vec3 *pPWMData_prev)
output voltage reconsturction to guarantee min duty in two phase at least
Detailed Description
Space Vector Generator (SVGEN) Module
Description
Package overview
The Space Vector Pulse Width Modulation (SVPWM) refers to a special switching sequence of the upper three power devices of a three-phase voltage source inverters (VSI) used in application such as AC induction and permanent magnet synchronous motor drives. This special switching scheme for the power devices results in 3 pseudo-sinusoidal currents in the stator phases.
It has been shown that SVPWM generates less harmonic distortion in the output voltages or currents in the windings of the motor load and provides more efficient use of DC supply voltage, in comparison to direct sinusoidal modulation technique. For the three phase power inverter configurations shown in Figure 1, there are eight possible combinations of on and off states of the upper power transistors. These combinations and the resulting instantaneous output line-to-line and phase voltages, for a dc bus voltage of VDC, are shown in Table 1.
By multiplexing in time the outputs of the inverter, it is possible to create AC signals with the inverter shown above. The typical output waveforms from space vector modulation are shown in the following figure. For this particular SVM example, alternating null vectors are used:
Simulation Information
The following figure shows a top level simulation model in Simulink.
The following figure shows the error in the calculation by the microcontroller, and compares it agains simulation output from Simulink.
Errors Ta, Tb and Tc are the microcontroller output minus Simulink output for function SVGEN_run().
Outputs shows both microcontroller and Simulink outputs for one output of SVGEN_run().
Configuration Information
Please see the SVGEN_init(), SVGEN_setup() and SVGEN_run() functions define in svgen.h for more details.
Integration Information
There is only one module in this package, the APIs can be referenced at SVGEN. The API headers can be located at svgen.h.
Typedef Documentation
SVGEN_Obj
typedef struct _SVGEN_Obj_ SVGEN_Obj
Defines the Space Vector Generator (SVGEN) object.
SVGEN_Handle
typedef struct _SVGEN_Obj_* SVGEN_Handle
Defines the SVGEN handle.
SVGENCURRENT_Obj
typedef struct _SVGENCURRENT_Obj_ SVGENCURRENT_Obj
Defines the Svgen Current object.
SVGENCURRENT_Handle
typedef struct _SVGENCURRENT_Obj_* SVGENCURRENT_Handle
Defines the Svgen Current handle.
Enumeration Type Documentation
SVM_Mode_e
enum SVM_Mode_e
Enumeration for svpwm mode.
Enumerator
SVM_COM_C
SVPWM common SVM mode.
SVM_MIN_C
DPWM minimum SVM mode.
SVM_MAX_C
DPWM maximum SVM.
SVM_DQ_S
SVPWM standard DQ mode.
SVGENCURRENT_IgnoreShunt_e
enum SVGENCURRENT_IgnoreShunt_e
Enumerator
SVGENCURRENT_USE_ALL
Use all shunt measurements.
SVGENCURRENT_IGNORE_A
Ignore the A phase shunt measurement.
SVGENCURRENT_IGNORE_B
Ignore the B phase shunt measurement.
SVGENCURRENT_IGNORE_C
Ignore the C phase shunt measurement.
SVGENCURRENT_IGNORE_AB
Ignore the AB phase shunt measurement.
SVGENCURRENT_IGNORE_AC
Ignore the AC phase shunt measurement.
SVGENCURRENT_IGNORE_BC
Ignore the BC phase shunt measurement.
SVGENCURRENT_IGNORE_ALL
Ignore the ABC phase shunt measurement.
SVGENCURRENT_MeasureShunt_e
enum SVGENCURRENT_MeasureShunt_e
Enumerator
SVGENCURRENT_ALL_PHASE_MEASURABLE
all shunt measurable
SVGENCURRENT_TWO_PHASE_MEASURABLE
just two shunt measurable
SVGENCURRENT_ONE_PHASE_MEASURABLE
just one shunt measurable
SVGENCURRENT_IMMEASUREABLE
SVGENCURRENT_VmidShunt_e
enum SVGENCURRENT_VmidShunt_e
Enumerator
SVGENCURRENT_VMID_A
Middle voltage is A phase.
SVGENCURRENT_VMID_B
Middle voltage is B phase.
SVGENCURRENT_VMID_C
Middle voltage is C phase.
Function Documentation
SVGEN_getOneOverDcBus_invV()
static float32_t SVGEN_getOneOverDcBus_invV (SVGEN_Handle handle) inline static
Gets the one over DC bus voltage value.
Parameters
[in] handle The space vector generator (SVGEN) handle
Returns
The inverse DC bus voltage value, 1/V
References _SVGEN_Obj_::oneOverDcBus_invV.
Referenced by SVGEN_run().
SVGEN_getMode()
static SVM_Mode_e SVGEN_getMode (SVGEN_Handle handle) inline static
Gets the spave vector mode.
Parameters
[in] handle The space vector generator (SVGEN) handle
Returns
The mode value of spave vector
References _SVGEN_Obj_::svmMode.
Referenced by SVGEN_run().
SVGEN_getSector()
static uint16_t SVGEN_getSector (SVGEN_Handle handle) inline static
Gets the spave vector sector value.
Parameters
[in] handle The space vector generator (SVGEN) handle
Returns
The sector value of spave vector
References _SVGEN_Obj_::sector.
SVGEN_setOneOverDcBus_invV()
static void SVGEN_setOneOverDcBus_invV (SVGEN_Handle handle, const float32_t oneOverDcBus_invV) inline static
Sets the one over DC bus voltage value.
Parameters
[in] handle The space vector generator (SVGEN) handle
[in] oneOverVbus_invV The inverse DC bus voltage value, 1/V
Returns
None
References _SVGEN_Obj_::oneOverDcBus_invV.
Referenced by SVGEN_setup().
SVGEN_setMode()
static void SVGEN_setMode (SVGEN_Handle handle, SVM_Mode_e svmMode) inline static
Sets the spave vector mode.
Parameters
[in] handle The space vector generator (SVGEN) handle
[in] svmMode The mode of spave vector
Returns
N/A
References _SVGEN_Obj_::svmMode.
SVGEN_setSector()
static void SVGEN_setSector (SVGEN_Handle handle, uint16_t sector) inline static
Sets the spave vector sector value.
Parameters
[in] handle The space vector generator (SVGEN) handle
[in] sector The sector value of spave vector
Returns
N/A
References _SVGEN_Obj_::sector.
SVGEN_setup()
static void SVGEN_setup (SVGEN_Handle handle, const float32_t oneOverDcBus_invV) inline static
Sets up the space vector generator (SVGEN) module.
Parameters
[in] handle The space vector generator (SVGEN) handle
[in] oneOverDcBus_invV The inverse DC bus voltage value, 1/V
Returns
None
References _SVGEN_Obj_::oneOverDcBus_invV, and SVGEN_setOneOverDcBus_invV().
SVGEN_init()
SVGEN_Handle SVGEN_init (void * pMemory, const size_t numBytes)
Initializes the space vector generator module.
Parameters
[in] pMemory A pointer to the space vector generator object memory
[in] numBytes The number of bytes allocated for the space vector generator object, bytes
Returns
The state vector generator (SVGEN) object handle
SVGEN_run()
static void SVGEN_run (SVGEN_Handle handle, const MATH_Vec2 * pVab_V, MATH_Vec3 * pVabc_pu) inline static
Implements a SVM that saturates at the level of MaxModulation.
Parameters
[in] handle The space vector generator (SVGEN) handle
[in] pVab_V The pointer to the alpha/beta voltages, V
[in] pVabc_pu The pointer to the three phase voltages, pu
Returns
None
References MATH_SQRTTHREE_OVER_TWO, _SVGEN_Obj_::oneOverDcBus_invV, SVGEN_getMode(), SVGEN_getOneOverDcBus_invV(), SVM_COM_C, SVM_MAX_C, SVM_MIN_C, _SVGEN_Obj_::svmMode, _MATH_Vec2_::value, and _MATH_Vec3_::value.
SVGENCURRENT_init()
SVGENCURRENT_Handle SVGENCURRENT_init (void * pMemory, const size_t numBytes)
Initializes the svgen current object.
Parameters
[in] *pMemory Pointer in to the svgen current object
[in] numBytes Size of the object
cla_SVGENCURRENT_init()
SVGENCURRENT_Handle cla_SVGENCURRENT_init (void * pMemory, const size_t numBytes)
SVGENCURRENT_setup()
void SVGENCURRENT_setup (SVGENCURRENT_Handle handle, const float32_t minWidth_usec, const float32_t pwmFreq_kHz, const float32_t systemFreq_MHz)
Sets up the PWM minimum width.
Parameters
[in] handle The svgen current (SVGEN) handle
[in] minWidth_usec The minimum pwm width
Returns
None
SVGENCURRENT_setMinWidth()
static void SVGENCURRENT_setMinWidth (SVGENCURRENT_Handle handle, const int16_t minwidth) inline static
Sets the minimum Duty Cycle width that the lower switch can be on before.
the current data is invalid.
Parameters
[in] handle The Svgen Current handle
[in] minwidth Integer value of the minimum number of pwm counts
References _SVGENCURRENT_Obj_::minWidth.
SVGENCURRENT_setIgnoreShunt()
static void SVGENCURRENT_setIgnoreShunt (SVGENCURRENT_Handle handle, const SVGENCURRENT_IgnoreShunt_e ignoreShunt) inline static
Sets the ignore shunt value.
Parameters
[in] handle The Svgen Current handle
[in] ignoreShunt The ignore shunt value
References _SVGENCURRENT_Obj_::ignoreShunt.
SVGENCURRENT_setMode()
static void SVGENCURRENT_setMode (SVGENCURRENT_Handle handle, const SVGENCURRENT_MeasureShunt_e compMode) inline static
Sets the compensation mode.
Parameters
[in] handle The Svgen Current handle
[in] CompMode CompMode
References _SVGENCURRENT_Obj_::compMode.
SVGENCURRENT_setVlimit()
static void SVGENCURRENT_setVlimit (SVGENCURRENT_Handle handle, const float32_t Vlimit) inline static
Sets the output voltage limit value for gurrantee a current sampling.
Parameters
[in] handle The Svgen Current handle
[in] Vlimit Vlimit
References _SVGENCURRENT_Obj_::Vlimit.
SVGENCURRENT_getIgnoreShunt()
static SVGENCURRENT_IgnoreShunt_e SVGENCURRENT_getIgnoreShunt (SVGENCURRENT_Handle handle) inline static
Gets the ignore shunt value.
Parameters
[in] handle The Svgen Current handle
Returns
Ignore shunt value
References _SVGENCURRENT_Obj_::ignoreShunt.
SVGENCURRENT_getMinWidth()
static int16_t SVGENCURRENT_getMinWidth (SVGENCURRENT_Handle handle) inline static
Gets the minimum Duty Cycle width that the lower switch can be on before.
the current data is invalid.
Parameters
[in] handle The Svgen Current handle
Returns
Integer value of the minimum number of pwm counts
References _SVGENCURRENT_Obj_::minWidth.
SVGENCURRENT_getVlimit()
static float32_t SVGENCURRENT_getVlimit (SVGENCURRENT_Handle handle) inline static
Gets the Voltage(Duty) Limit value.
Parameters
[in] handle The Svgen Current handle
Returns
Integer value of the voltage(duty) limit
References _SVGENCURRENT_Obj_::Vlimit.
SVGENCURRENT_getMode()
static SVGENCURRENT_MeasureShunt_e SVGENCURRENT_getMode (SVGENCURRENT_Handle handle) inline static
Gets the current reconstruction mode.
Parameters
[in] handle The Svgen Current handle
Returns
CompMode
References _SVGENCURRENT_Obj_::compMode.
SVGENCURRENT_getVmid()
static SVGENCURRENT_VmidShunt_e SVGENCURRENT_getVmid (SVGENCURRENT_Handle handle) inline static
Gets the middle amplitude voltage.
Parameters
[in] handle The Svgen Current handle
Returns
middle voltage
References _SVGENCURRENT_Obj_::Vmid.
SVGENCURRENT_RunIgnoreShunt()
static void SVGENCURRENT_RunIgnoreShunt (SVGENCURRENT_Handle handle, uint16_t cmp1, uint16_t cmp2, uint16_t cmp3, uint16_t cmpM1, uint16_t cmpM2, uint16_t cmpM3) inline static
Gets the svgen current module ignore shunt.
In the pwm structure, the value variable is the on-time of the low fet.
A low value is a small on-time for the low switch of the bridge and thus a short current window.
Parameters
[in] handle The Svgen Current handle
[in] cmp1 compare value 1
[in] cmp2 compare value 2
[in] cmp3 compare value 3
[in] cmpM1 active compare value 1, from mirror register
[in] cmpM2 active compare value 2, from mirror register
[in] cmpM3 active compare value 3, from mirror register
References _SVGENCURRENT_Obj_::ignoreShunt, _SVGENCURRENT_Obj_::minWidth, SVGENCURRENT_IGNORE_A, SVGENCURRENT_IGNORE_AB, SVGENCURRENT_IGNORE_AC, SVGENCURRENT_IGNORE_B, SVGENCURRENT_IGNORE_BC, SVGENCURRENT_IGNORE_C, and SVGENCURRENT_USE_ALL.
SVGENCURRENT_RunRegenCurrent()
static void SVGENCURRENT_RunRegenCurrent (SVGENCURRENT_Handle handle, MATH_Vec3 * pADCData, MATH_Vec3 * pADCDataPrev) inline static
Reconstructs the missed measured currents due to a small sampling window.
Parameters
[in] handle The svgen current handle
[in] pADCData Pointer to the shunt currents
References _SVGENCURRENT_Obj_::compMode, _SVGENCURRENT_Obj_::ignoreShunt, SVGENCURRENT_IGNORE_A, SVGENCURRENT_IGNORE_AB, SVGENCURRENT_IGNORE_AC, SVGENCURRENT_IGNORE_B, SVGENCURRENT_IGNORE_BC, SVGENCURRENT_IGNORE_C, SVGENCURRENT_TWO_PHASE_MEASURABLE, and _MATH_Vec3_::value.
SVGENCURRENT_compPWMData()
static void SVGENCURRENT_compPWMData (SVGENCURRENT_Handle handle, MATH_Vec3 * pPWMData, MATH_Vec3 * pPWMData_prev) inline static
output voltage reconsturction to guarantee min duty in two phase at least
Parameters
[in] handle The svgen current handle
[in] pPWMData The pointer of the PWM data
[in] pPWMData_old The pointer of old PWM data
References _SVGENCURRENT_Obj_::compMode, _SVGENCURRENT_Obj_::ignoreShunt, SVGENCURRENT_ALL_PHASE_MEASURABLE, SVGENCURRENT_IGNORE_A, SVGENCURRENT_IGNORE_B, SVGENCURRENT_IGNORE_C, SVGENCURRENT_ONE_PHASE_MEASURABLE, SVGENCURRENT_TWO_PHASE_MEASURABLE, SVGENCURRENT_USE_ALL, SVGENCURRENT_VMID_A, SVGENCURRENT_VMID_B, SVGENCURRENT_VMID_C, _MATH_Vec3_::value, _SVGENCURRENT_Obj_::Vlimit, _SVGENCURRENT_Obj_::Vmid, and _SVGENCURRENT_Obj_::Voffset.
Copyright 2021, Texas Instruments Incorporated