STEP_RESPONSE
STEP_RESPONSE
Data Structures
struct _GRAPH_Buffer_t_
struct _GRAPH_StepVars_t_
Macros
#define GRAPH_BUFFER_NR 2
#define GRAPH_BUFFER_SIZE 256
#define GRAPH_BUFFER_MASK (256-1)
#define GRAPH_BUFFER_SPEED_TICK 100U
#define GRAPH_BUFFER_CURRENT_TICK 10U
#define GRAPH_SPEEDREF_DEFAULT 40.0f
#define GRAPH_SPEEDREF_STEP 60.0f
#define GRAPH_CURRENTREF_DEFAULT 0.0f
#define GRAPH_CURRENTREF_STEP -0.5f
#define GRAPH_TORQUE_DEFAULT 1.0f
#define GRAPH_TORQUE_STEP 4.0f
Typedefs
typedef struct _GRAPH_Buffer_t_ GRAPH_Buffer_t
typedef struct _GRAPH_StepVars_t_ GRAPH_StepVars_t
Enumerations
enum GRAPH_BufferNR_e {
GRAPH_BUFFER_NR0 =0,
GRAPH_BUFFER_NR1,
GRAPH_BUFFER_NR2,
GRAPH_BUFFER_NR3,
GRAPH_BUFFER_NR0 = 0,
GRAPH_BUFFER_NR1 = 1
}
Initialization values of global variables.
enum GRAPH_STEP_RPM_Mode_e {
GRAPH_STEP_RP_IDLE = 0,
GRAPH_STEP_RP_CURRENT = 1,
GRAPH_STEP_RP_SPEED = 2,
GRAPH_STEP_RP_TORQUE = 3
}
Functions
static bool GRAPH_writeDataBuffer (GRAPH_Buffer_t *pBuffer, float32_t data)
Write into the buffer.
void GRAPH_generateStepResponse (GRAPH_StepVars_t *pStepVars)
Sets the values to collect in a data array.
void GRAPH_init (GRAPH_StepVars_t *pStepVars, volatile float32_t *pSpeed_ref, volatile float32_t *pSpeed_in, volatile float32_t *pId_ref, volatile float32_t *pId_in, volatile float32_t *pIq_ref, volatile float32_t *pIq_in)
Data gathering function for any iq value.
static void GRAPH_collectData (GRAPH_StepVars_t *pStepVars, GRAPH_BufferNR_e bufferNum, float32_t gData)
Data gathering function for any iq value.
static GRAPH_STEP_RPM_Mode_e GRAPH_getBufferMode (GRAPH_StepVars_t *pStepVars)
static void GRAPH_updateBuffer (GRAPH_StepVars_t *pStepVars)
Sets the values to collect in a data array.
Detailed Description
Macro Definition Documentation
GRAPH_BUFFER_NR
#define GRAPH_BUFFER_NR 2
GRAPH_BUFFER_SIZE
#define GRAPH_BUFFER_SIZE 256
GRAPH_BUFFER_MASK
#define GRAPH_BUFFER_MASK (256-1)
GRAPH_BUFFER_SPEED_TICK
#define GRAPH_BUFFER_SPEED_TICK 100U
GRAPH_BUFFER_CURRENT_TICK
#define GRAPH_BUFFER_CURRENT_TICK 10U
GRAPH_SPEEDREF_DEFAULT
#define GRAPH_SPEEDREF_DEFAULT 40.0f
GRAPH_SPEEDREF_STEP
#define GRAPH_SPEEDREF_STEP 60.0f
GRAPH_CURRENTREF_DEFAULT
#define GRAPH_CURRENTREF_DEFAULT 0.0f
GRAPH_CURRENTREF_STEP
#define GRAPH_CURRENTREF_STEP -0.5f
GRAPH_TORQUE_DEFAULT
#define GRAPH_TORQUE_DEFAULT 1.0f
GRAPH_TORQUE_STEP
#define GRAPH_TORQUE_STEP 4.0f
Typedef Documentation
GRAPH_Buffer_t
typedef struct _GRAPH_Buffer_t_ GRAPH_Buffer_t
GRAPH_StepVars_t
typedef struct _GRAPH_StepVars_t_ GRAPH_StepVars_t
Enumeration Type Documentation
GRAPH_BufferNR_e
enum GRAPH_BufferNR_e
Initialization values of global variables.
Enumeration for the number of buffers
Enumerator
GRAPH_BUFFER_NR0
Buffer define 0.
GRAPH_BUFFER_NR1
Buffer define 1.
GRAPH_BUFFER_NR2
Buffer define 2.
GRAPH_BUFFER_NR3
Buffer define 3.
GRAPH_BUFFER_NR0
Buffer define 0.
GRAPH_BUFFER_NR1
Buffer define 1.
GRAPH_STEP_RPM_Mode_e
enum GRAPH_STEP_RPM_Mode_e
Enumerator
GRAPH_STEP_RP_IDLE
current step response
GRAPH_STEP_RP_CURRENT
d-axis current step response
GRAPH_STEP_RP_SPEED
speed step response
GRAPH_STEP_RP_TORQUE
q-axis current step response
Function Documentation
GRAPH_writeDataBuffer()
static bool GRAPH_writeDataBuffer (GRAPH_Buffer_t * pBuffer, float32_t data) inline static
Write into the buffer.
Parameters
[in] GRAPH_Buffer_t The pointer to the buffer data
[in] word Write data into the buffer
References _GRAPH_Buffer_t_::data, GRAPH_BUFFER_MASK, and _GRAPH_Buffer_t_::write.
Referenced by GRAPH_collectData().
GRAPH_generateStepResponse()
void GRAPH_generateStepResponse (GRAPH_StepVars_t * pStepVars)
Sets the values to collect in a data array.
Parameters
[in] handle The controller (CTRL) handle
[in] pGraphVars Pointer to the graph variables
[in] pStepVars Pointer to the step variables
GRAPH_init()
void GRAPH_init (GRAPH_StepVars_t * pStepVars, volatile float32_t * pSpeed_ref, volatile float32_t * pSpeed_in, volatile float32_t * pId_ref, volatile float32_t * pId_in, volatile float32_t * pIq_ref, volatile float32_t * pIq_in)
Data gathering function for any iq value.
Parameters
[in] pGraphVars Pointer to the graph variables
[in] pSpeed_in The pointer to the speed feedback data
[in] pId_in The pointer to the Id feedback data
[in] pIq_in The pointer to the Iq feedback data
[in] pSpeed_ref The pointer to the speed reference data
[in] pId_ref The pointer to the Id reference data
GRAPH_collectData()
static void GRAPH_collectData (GRAPH_StepVars_t * pStepVars, GRAPH_BufferNR_e bufferNum, float32_t gData) inline static
Data gathering function for any iq value.
Parameters
[in] GRAPH_Vars_t The pointer to the gGraphVars data
[in] GRAPH_BufferNR_e Definition of buffer number
[in] gData Recorded iq data
[in] TriggerValue Trigger value to start the data recording
References _GRAPH_StepVars_t_::bufferCounter, _GRAPH_StepVars_t_::bufferData, _GRAPH_StepVars_t_::bufferTick, _GRAPH_StepVars_t_::bufferTickCounter, GRAPH_BUFFER_NR0, GRAPH_BUFFER_SIZE, and GRAPH_writeDataBuffer().
Referenced by GRAPH_updateBuffer().
GRAPH_getBufferMode()
static GRAPH_STEP_RPM_Mode_e GRAPH_getBufferMode (GRAPH_StepVars_t * pStepVars) inline static
References _GRAPH_StepVars_t_::bufferMode.
GRAPH_updateBuffer()
static void GRAPH_updateBuffer (GRAPH_StepVars_t * pStepVars) inline static
Sets the values to collect in a data array.
Parameters
[in] handle The controller (CTRL) handle
[in] pGraphVars Pointer to the graph variables
[in] pStepVars Pointer to the step variables
References _GRAPH_StepVars_t_::bufferMode, GRAPH_BUFFER_NR0, GRAPH_BUFFER_NR1, GRAPH_collectData(), GRAPH_STEP_RP_CURRENT, GRAPH_STEP_RP_SPEED, GRAPH_STEP_RP_TORQUE, _GRAPH_StepVars_t_::pId_in, _GRAPH_StepVars_t_::pIq_in, and _GRAPH_StepVars_t_::pSpeed_in.
Copyright 2021, Texas Instruments Incorporated