TRAJ
TRAJ
Data Structures
struct _TRAJ_Obj_
Defines the trajectory (TRAJ) object.
Typedefs
typedef struct _TRAJ_Obj_ TRAJ_Obj
Defines the trajectory (TRAJ) object.
typedef struct _TRAJ_Obj_ * TRAJ_Handle
Defines the TRAJ handle.
Functions
static float32_t TRAJ_getIntValue (TRAJ_Handle handle)
Gets the intermediate value for the trajectory.
static float32_t TRAJ_getMaxDelta (TRAJ_Handle handle)
Gets the maximum delta value for the trajectory.
static float32_t TRAJ_getMaxValue (TRAJ_Handle handle)
Gets the maximum value for the trajectory.
static float32_t TRAJ_getMinValue (TRAJ_Handle handle)
Gets the minimum value for the trajectory.
static float32_t TRAJ_getTargetValue (TRAJ_Handle handle)
Gets the target value for the trajectory.
TRAJ_Handle TRAJ_init (void *pMemory, const size_t numBytes)
Initializes the trajectory (TRAJ) object.
TRAJ_Handle cla_TRAJ_init (void *pMemory, const size_t numBytes)
static void TRAJ_setIntValue (TRAJ_Handle handle, const float32_t intValue)
Sets the intermediate value for the trajectory.
static void TRAJ_setMaxDelta (TRAJ_Handle handle, const float32_t maxDelta)
Sets the maximum delta value for the trajectory.
static void TRAJ_setMaxValue (TRAJ_Handle handle, const float32_t maxValue)
Sets the maximum value for the trajectory.
static void TRAJ_setMinValue (TRAJ_Handle handle, const float32_t minValue)
Sets the minimum value for the trajectory.
static void TRAJ_setTargetValue (TRAJ_Handle handle, const float32_t targetValue)
Sets the target value for the trajectory.
static void TRAJ_run (TRAJ_Handle handle)
Runs the trajectory (TRAJ) object.
Detailed Description
Trajectory (TRAJ) Module
Description
Package overview
In this implementation the frequency of the ramp output is controlled by a precision frequency generation algorithm which relies on the modulo nature (i.e. wrap-around) of finite length variables in 28xx. One such variable, called (a data memory location in 28xx) in this implementation, is used as a variable to determine the minimum of the ramp signal. Adding a fixed step value to the Angle variable causes the value in Angle to cycle at a constant rate.
At the end limit the value in simply wraps around and continues at the next modulo value given by the step size. For a given step size, the frequency of the ramp output (in Hz) is given by:
where
is the sampling loop frequency in Hz
is the number of bits in the auto wrapper variable
From the above equation it is clear that a value of 1 gives: when and .
where is the sampling period in seconds.
Configuration Information
Please see the TRAJ_init() and TRAJ_run() functions defined in traj.h for more details.
Integration Information
There is only one module in this package, the APIs can be referenced at TRAJ. The API headers can be located at traj.h.
Typedef Documentation
TRAJ_Obj
typedef struct _TRAJ_Obj_ TRAJ_Obj
Defines the trajectory (TRAJ) object.
TRAJ_Handle
typedef struct _TRAJ_Obj_* TRAJ_Handle
Defines the TRAJ handle.
Function Documentation
TRAJ_getIntValue()
static float32_t TRAJ_getIntValue (TRAJ_Handle handle) inline static
Gets the intermediate value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
Returns
The intermediate value
References _TRAJ_Obj_::intValue.
Referenced by TRAJ_run().
TRAJ_getMaxDelta()
static float32_t TRAJ_getMaxDelta (TRAJ_Handle handle) inline static
Gets the maximum delta value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
Returns
The maximum delta value
References _TRAJ_Obj_::maxDelta.
Referenced by TRAJ_run().
TRAJ_getMaxValue()
static float32_t TRAJ_getMaxValue (TRAJ_Handle handle) inline static
Gets the maximum value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
Returns
The maximum value
References _TRAJ_Obj_::maxValue.
Referenced by TRAJ_run().
TRAJ_getMinValue()
static float32_t TRAJ_getMinValue (TRAJ_Handle handle) inline static
Gets the minimum value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
Returns
The minimum value
References _TRAJ_Obj_::minValue.
Referenced by TRAJ_run().
TRAJ_getTargetValue()
static float32_t TRAJ_getTargetValue (TRAJ_Handle handle) inline static
Gets the target value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
Returns
The target value
References _TRAJ_Obj_::targetValue.
Referenced by TRAJ_run().
TRAJ_init()
TRAJ_Handle TRAJ_init (void * pMemory, const size_t numBytes)
Initializes the trajectory (TRAJ) object.
Parameters
[in] pMemory A pointer to the memory for the trajectory (TRAJ) object
[in] numBytes The number of bytes allocated for the trajectory object, bytes
Returns
The trajectory (TRAJ) object handle
cla_TRAJ_init()
TRAJ_Handle cla_TRAJ_init (void * pMemory, const size_t numBytes)
TRAJ_setIntValue()
static void TRAJ_setIntValue (TRAJ_Handle handle, const float32_t intValue) inline static
Sets the intermediate value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
[in] intValue The intermediate value
Returns
None
References _TRAJ_Obj_::intValue.
Referenced by TRAJ_run().
TRAJ_setMaxDelta()
static void TRAJ_setMaxDelta (TRAJ_Handle handle, const float32_t maxDelta) inline static
Sets the maximum delta value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
[in] maxDelta The maximum delta value
Returns
None
References _TRAJ_Obj_::maxDelta.
TRAJ_setMaxValue()
static void TRAJ_setMaxValue (TRAJ_Handle handle, const float32_t maxValue) inline static
Sets the maximum value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
[in] maxValue The maximum value
Returns
None
References _TRAJ_Obj_::maxValue.
TRAJ_setMinValue()
static void TRAJ_setMinValue (TRAJ_Handle handle, const float32_t minValue) inline static
Sets the minimum value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
[in] minValue The minimum value
Returns
None
References _TRAJ_Obj_::minValue.
TRAJ_setTargetValue()
static void TRAJ_setTargetValue (TRAJ_Handle handle, const float32_t targetValue) inline static
Sets the target value for the trajectory.
Parameters
[in] handle The trajectory (TRAJ) handle
[in] targetValue The target value
Returns
None
References _TRAJ_Obj_::targetValue.
TRAJ_run()
static void TRAJ_run (TRAJ_Handle handle) inline static
Runs the trajectory (TRAJ) object.
Parameters
[in] handle The trajectory (TRAJ) handle
Returns
None
References _TRAJ_Obj_::intValue, MATH_sat(), _TRAJ_Obj_::maxDelta, _TRAJ_Obj_::maxValue, _TRAJ_Obj_::minValue, _TRAJ_Obj_::targetValue, TRAJ_getIntValue(), TRAJ_getMaxDelta(), TRAJ_getMaxValue(), TRAJ_getMinValue(), TRAJ_getTargetValue(), and TRAJ_setIntValue().
Copyright 2021, Texas Instruments Incorporated