sfra_examples_hal.h File Reference
sfra_examples_hal.h File Reference
#include "inc/hw_types.h"
#include "driverlib.h"
#include "device.h"
#include "sfra_examples_settings.h"
Macros
#define FALSE 0
#define TRUE 1
#define PWM_TRIP_STATUS EPWM_getTripZoneFlagStatus
#define ADC_PU_SCALE_FACTOR (float)(0.000244140625)
#define ADC_PU_PPB_SCALE_FACTOR 0.000488281250
#define GET_TASK_A_TIMER_OVERFLOW_STATUS CPUTimer_getTimerOverflowStatus(CPUTIMER0_BASE)
#define CLEAR_TASK_A_TIMER_OVERFLOW_FLAG CPUTimer_clearOverflowFlag(CPUTIMER0_BASE)
#define GET_TASK_B_TIMER_OVERFLOW_STATUS CPUTimer_getTimerOverflowStatus(CPUTIMER1_BASE)
#define CLEAR_TASK_B_TIMER_OVERFLOW_FLAG CPUTimer_clearOverflowFlag(CPUTIMER1_BASE)
Functions
void setupDevice (void)
void setupADC (void)
void setupUpDwnCountPWM (uint32_t base1, uint16_t pwm_period_ticks)
void disablePWMCLKCounting (void)
void enablePWMCLKCounting (void)
void setPinsAsPWM ()
void setupProfilingGPIO ()
interrupt void controlISR (void)
static void setProfilingGPIO (void)
static void resetProfilingGPIO (void)
static void setProfilingGPIO2 (void)
static void resetProfilingGPIO2 (void)
static void clearPWMInterruptFlag (uint32_t base)
static void enablePWMInterruptGeneration (uint32_t base)
static void clearInterrupt (uint16_t pie_group_no)
static void setupInterrupt (void)
Macro Definition Documentation
FALSE
#define FALSE 0
TRUE
#define TRUE 1
PWM_TRIP_STATUS
#define PWM_TRIP_STATUS EPWM_getTripZoneFlagStatus
ADC_PU_SCALE_FACTOR
#define ADC_PU_SCALE_FACTOR (float)(0.000244140625)
ADC_PU_PPB_SCALE_FACTOR
#define ADC_PU_PPB_SCALE_FACTOR 0.000488281250
GET_TASK_A_TIMER_OVERFLOW_STATUS
#define GET_TASK_A_TIMER_OVERFLOW_STATUS CPUTimer_getTimerOverflowStatus(CPUTIMER0_BASE)
CLEAR_TASK_A_TIMER_OVERFLOW_FLAG
#define CLEAR_TASK_A_TIMER_OVERFLOW_FLAG CPUTimer_clearOverflowFlag(CPUTIMER0_BASE)
GET_TASK_B_TIMER_OVERFLOW_STATUS
#define GET_TASK_B_TIMER_OVERFLOW_STATUS CPUTimer_getTimerOverflowStatus(CPUTIMER1_BASE)
CLEAR_TASK_B_TIMER_OVERFLOW_FLAG
#define CLEAR_TASK_B_TIMER_OVERFLOW_FLAG CPUTimer_clearOverflowFlag(CPUTIMER1_BASE)
Function Documentation
setupDevice()
void setupDevice (void)
setupADC()
void setupADC (void)
setupUpDwnCountPWM()
void setupUpDwnCountPWM (uint32_t base1, uint16_t pwm_period_ticks)
disablePWMCLKCounting()
void disablePWMCLKCounting (void)
enablePWMCLKCounting()
void enablePWMCLKCounting (void)
setPinsAsPWM()
void setPinsAsPWM ()
setupProfilingGPIO()
void setupProfilingGPIO ()
controlISR()
interrupt void controlISR (void)
Referenced by setupInterrupt().
setProfilingGPIO()
static void setProfilingGPIO (void) inline static
References GPIO_PROFILING1_SET.
Referenced by controlCode().
resetProfilingGPIO()
static void resetProfilingGPIO (void) inline static
References GPIO_PROFILING1_CLEAR.
Referenced by controlCode().
setProfilingGPIO2()
static void setProfilingGPIO2 (void) inline static
References GPIO_PROFILING2_SET.
resetProfilingGPIO2()
static void resetProfilingGPIO2 (void) inline static
References GPIO_PROFILING2_CLEAR.
clearPWMInterruptFlag()
static void clearPWMInterruptFlag (uint32_t base) inline static
Referenced by controlCode().
enablePWMInterruptGeneration()
static void enablePWMInterruptGeneration (uint32_t base) inline static
References CNTRL_ISR_FREQ_RATIO.
Referenced by setupInterrupt().
clearInterrupt()
static void clearInterrupt (uint16_t pie_group_no) inline static
Referenced by setupInterrupt().
setupInterrupt()
static void setupInterrupt (void) inline static
References C28x_CONTROLISR_INTERRUPT, C28x_CONTROLISR_INTERRUPT_PIE_GROUP_NO, C28x_CONTROLISR_INTERRUPT_TRIG_PWM_BASE, clearInterrupt(), controlISR(), and enablePWMInterruptGeneration().
Copyright 2021, Texas Instruments Incorporated