 /* Info.obj: */  -u Fapi_getLibraryInfo
 /* Init.obj: */ -u Fapi_initializeAPI
 /* FlashStateMachine.obj: */ -u Fapi_setActiveFlashBank
 /* Async.obj: */ -u Fapi_issueAsyncCommandWithAddress
 /* BlankCheck.obj: */ -u Fapi_doBlankCheck
 /* Program.obj: */ -u Fapi_issueProgrammingCommand
 /* Program.obj: */ -u Fapi_issueProgrammingCommandForEccAddresses
 /* Verify.obj: */ -u Fapi_doVerify
 /* Verify.obj: */ -u Fapi_doVerifyBy16bits
 /* Async.obj: */ -u Fapi_issueAsyncCommand
 /* FlashStateMachine.obj: */ -u Fapi_issueFsmSuspendCommand
 /* FlashStateMachine.obj: */ -u Fapi_checkFsmForReady
 /* FlashStateMachine.obj: */ -u Fapi_getFsmStatus
 /* Utilities.obj: */ -u Fapi_calculateEcc
 /* Utilities.obj: */ -u Fapi_calculateFletcherChecksum
 /* FlashStateMachine.obj: */ -u Fapi_isAddressEcc
 /* FlashStateMachine.obj: */ -u Fapi_remapEccAddress
 /* Read.obj: */ -u Fapi_flushPipeline
 /* Psa.obj: */ -u Fapi_calculatePsa
 /* Psa.obj: */ -u Fapi_doPsaVerify
