CPU Register API Functions
CPU Register API Functions
Macros
#define STL_CPU_REG_PASS 0x0U
#define STL_CPU_REG_FAIL 0x1U
Functions
uint16_t STL_CPU_REG_testCPURegisters (bool injectError)
uint16_t STL_CPU_REG_testFPURegisters (bool injectError)
uint16_t STL_CPU_REG_testVCURegisters (uint32_t *scratchRAM, bool injectError)
static uint16_t STL_CPU_REG_checkCPURegisters (bool injectError)
Tests CPU registers.
static uint16_t STL_CPU_REG_checkFPURegisters (bool injectError)
Tests FPU registers.
static uint16_t STL_CPU_REG_checkVCURegisters (bool injectError)
Tests VCU registers.
Detailed Description
The code for this module is contained in source/stl_cpu_reg.c and source/stl_cpu_reg_s.asm, with include/stl_cpu_reg.h containing the API declarations for use by applications.
Error Injection
The functions in this module all have an injectError parameter that when set to true, will overwrite an incorrect test pattern to a register instead of the expected pattern in order to generate a failure.
Macro Definition Documentation
#define STL_CPU_REG_PASS 0x0U
Referenced by STL_CPU_REG_checkCPURegisters(), STL_CPU_REG_checkFPURegisters(), and STL_CPU_REG_checkVCURegisters().
#define STL_CPU_REG_FAIL 0x1U
Function Documentation
uint16_t STL_CPU_REG_testCPURegisters (bool injectError)
Referenced by STL_CPU_REG_checkCPURegisters().
uint16_t STL_CPU_REG_testFPURegisters (bool injectError)
Referenced by STL_CPU_REG_checkFPURegisters().
uint16_t STL_CPU_REG_testVCURegisters (uint32_t * scratchRAM, bool injectError)
Referenced by STL_CPU_REG_checkVCURegisters().
static uint16_t STL_CPU_REG_checkCPURegisters (bool injectError) inline static
Tests CPU registers.
Parameters
injectError when false the test writes the test pattern to the registers as expected. When true, the test will write an unexpected error pattern to ACC to simulate a stuck bit, causing the test to fail.
This function tests CPU core registers for stuck bits. The following registers are tested:
ACC
P
XAR0 to XAR7
XT
SP
IFR, IER and DBGIER
ST0
ST1 (excluding IDLESTAT and LOOP bits)
DP
The values of ST0, ST1, DP, IER, IFR, and DBGIER and the save-on-entry XAR registers, as defined by the compiler calling convention, are saved and restored in this test.
Note that the IDLESTAT and LOOP bits of ST1 are not tested by this function as they are read-only. IDLESTAT is set when the IDLE instruction is used to enter a low-power mode. Performing a functional test of the low-power mode will indirectly serve as a test of IDLESTAT.
The LOOP bit is set by the LOOPZ and LOOPNZ instructions. The C2000 compiler will not generate code that uses these instructions. If an application contains hand-coded assembly that uses them, the LOOP bit may also be tested by performing a functional test of the applicable LOOP instruction.
Note
You should disable interrupts before calling this test.
Returns
If the test passes, the routine returns STL_CPU_REG_PASS. Otherwise, it returns STL_CPU_REG_FAIL.
References STL_CPU_REG_PASS, STL_CPU_REG_testCPURegisters(), STL_UTIL_CPU_REG, and STL_Util_setErrorFlag().
static uint16_t STL_CPU_REG_checkFPURegisters (bool injectError) inline static
Tests FPU registers.
Parameters
injectError when false the test writes the test pattern to the registers as expected. When true, the test will write an unexpected error pattern to R5H to simulate a stuck bit, causing the test to fail.
This function tests FPU registers for stuck bits. The following registers are tested:
R0H to R7H
RND32, TF, ZI, NI, ZF, NF bits of STF register.
Shadow registers for R0H to R7H and STF
The values of STF and the save-on-entry RnH registers, as defined by the compiler calling convention, are saved and restored in this test.
Note
You should disable interrupts before calling this test.
Returns
If the test passes, the routine returns STL_CPU_REG_PASS. Otherwise, it returns STL_CPU_REG_FAIL.
References STL_CPU_REG_PASS, STL_CPU_REG_testFPURegisters(), STL_UTIL_FPU_REG, and STL_Util_setErrorFlag().
static uint16_t STL_CPU_REG_checkVCURegisters (bool injectError) inline static
Tests VCU registers.
Parameters
injectError when false the test writes the test pattern to the registers as expected. When true, the test will write an unexpected error pattern to VR4 to simulate a stuck bit, causing the test to fail.
This function tests VCU (Viterbi, Complex Math and CRC Unit) registers for stuck bits. The following registers are tested:
VR0 to VR8
VT0 and VT1
VCRC
VSTATUS
The value of VSTATUS saved and restored in this test.
Note
You should disable interrupts before calling this test.
Returns
If the test passes, the routine returns STL_CPU_REG_PASS. Otherwise, it returns STL_CPU_REG_FAIL.
References STL_CPU_REG_PASS, STL_CPU_REG_testVCURegisters(), STL_Util_setErrorFlag(), and STL_UTIL_VCU_REG.
Copyright 2021, Texas Instruments Incorporated