Utilities API Functions
Utilities API Functions
Macros
#define STL_UTIL_CPU_RATE 10.00f
Enumerations
enum STL_Util_ErrorFlag {
STL_UTIL_CRC = 0x00000001UL,
STL_UTIL_CPU_REG = 0x00000002UL,
STL_UTIL_FPU_REG = 0x00000004UL,
STL_UTIL_VCU_REG = 0x00000008UL,
STL_UTIL_PIE_RAM_MISMATCH = 0x00000010UL,
STL_UTIL_PIE_RAM_INT = 0x00000020UL,
STL_UTIL_OSC_TIMER2 = 0x00000040UL,
STL_UTIL_OSC_HR_MEP_RANGE = 0x00000080UL,
STL_UTIL_OSC_HR_SFO = 0x00000100UL,
STL_UTIL_OSC_HR_DELAY = 0x00000200UL,
STL_UTIL_MARCH = 0x00000400UL,
STL_UTIL_CAN_RAM_PARITY = 0x00000800UL
}
Functions
static void STL_Util_delayUS (uint32_t microseconds)
void STL_Util_setErrorFlag (const STL_Util_ErrorFlag errorFlag)
uint32_t STL_Util_getErrorFlag (void)
void STL_Util_clearErrorFlag (const STL_Util_ErrorFlag errorFlag)
Detailed Description
The code for this module is contained in source/stl_util.c and source/stl_util_s.asm, with include/stl_util.h containing the API declarations for use by applications.
Macro Definition Documentation
#define STL_UTIL_CPU_RATE 10.00f
Referenced by STL_Util_delayUS().
Enumeration Type Documentation
enum STL_Util_ErrorFlag
Values to be passed to STL_Util_setErrorFlag() and STL_Util_clearErrorFlag(). These correspond to different errors in the STL.
Enumerator
STL_UTIL_CRC
CRC check.
STL_UTIL_CPU_REG
CPU register test.
STL_UTIL_FPU_REG
FPU register test.
STL_UTIL_VCU_REG
VCU register test.
STL_UTIL_PIE_RAM_MISMATCH
PIE RAM.
STL_UTIL_PIE_RAM_INT
PIE RAM handler failed to execute.
STL_UTIL_OSC_TIMER2
OSC timer 2.
STL_UTIL_OSC_HR_MEP_RANGE
MEP out of range.
STL_UTIL_OSC_HR_SFO
SFO calibration error.
STL_UTIL_OSC_HR_DELAY
SFO delay error.
STL_UTIL_MARCH
March RAM test.
STL_UTIL_CAN_RAM_PARITY
March test for CAN message RAM.
Function Documentation
static void STL_Util_delayUS (uint32_t microseconds) inline static
Delay for a specified number of microseconds
Parameters
microseconds is the number of microseconds to delay.
This function calls SysCtl_delay() to achieve a delay in microseconds. The function will convert the desired delay in microseconds to the count value expected by the function. microseconds is the number of microseconds to delay.
Note
If this function does not get inlined (for instance, if the optimizer is turned off) the delay will be made less accurate by the overhead of the additional function call.
Returns
None.
References STL_UTIL_CPU_RATE.
void STL_Util_setErrorFlag (const STL_Util_ErrorFlag errorFlag)
Sets a global error flag.
Parameters
errorFlag is a STL_Util_ErrorFlag that will be set in globalErrorFlags.
This function sets an error flag in the global globalErrorFlags.
Returns
None.
Referenced by STL_CPU_REG_checkCPURegisters(), STL_CPU_REG_checkFPURegisters(), and STL_CPU_REG_checkVCURegisters().
uint32_t STL_Util_getErrorFlag (void)
Gets the error flag status of globalErrorFlags.
This function returns the global globalErrorFlags.
Returns
Returns the global globalErrorFlags.
void STL_Util_clearErrorFlag (const STL_Util_ErrorFlag errorFlag)
Clears a flag of globalErrorFlags.
Parameters
errorFlag is a STL_Util_ErrorFlag that will be cleared in globalErrorFlags.
This function clears a flag of globalErrorFlags.
Returns
None.
Copyright 2021, Texas Instruments Incorporated